server:
  port: 8078
  servlet:
#    context-path: /core
    application-display-name: oss

aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      accessKeyId: yourAccessKeyId
      accessKeySecret: yourAccessKeySecret
      bucketName: yourBucketName

  ##  String endpoint = "http://oss-cn-hangzhou.aliyuncs.com";
  ##  // 阿里云主账号AccessKey拥有所有API的访问权限，风险很高。强烈建议您创建并使用RAM账号进行API访问或日常运维，请登录 https://ram.console.aliyun.com 创建RAM账号。
  ##  String accessKeyId = "<yourAccessKeyId>";
  ##  String accessKeySecret = "<yourAccessKeySecret>";
  ##  String bucketName = "<yourBucketName>";