server:
  port: 8079
  servlet:
#    context-path: /core
    application-display-name: edu

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/online_edu_site?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8

  # 设置时间格式和时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

# 日志
#logging:
#  level:
#    root: info  # OFF, FATAL, ERROR, WARN, INFO, DEBUG, ALL （后面的级别包含前面的级别）

